version: '3.8'

services:
  node:
    build:
      context: ./node
    container_name: node
    ports:
      - "8080:4785"
    networks:
      - starnet
    volumes:
      - ./node:/node

  postgres_server:
    image: postgres:alpine
    container_name: postgres_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: metrics_db
    ports:
      - "8082:5432"
    networks:
      - starnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "8081:8777"
    networks:
      - starnet
    volumes:
      - ./client:/client

networks:
  starnet:
    driver: bridge

volumes:
  postgres_data:
    driver: local
